### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alishaaman** [NightingaleHealth/ggforestplot#4] opened 2021-04-06 09:05 UTC
Hi there,
I cannot seem to install the package on R? I am using R 4.0.5 on Windows 64bit

> devtools::install_github("NightingaleHealth/ggforestplot")
Downloading GitHub repo NightingaleHealth/ggforestplot@HEAD
√  checking for file 'C:\Users\alish\AppData\Local\Temp\RtmpUpSUza\remotes112038ba7599\NightingaleHealth-ggforestplot-547617e/DESCRIPTION' ...
-  preparing 'ggforestplot': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ggforestplot_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/alish/OneDrive/My Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'ggforestplot' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ggforestplot'
    finding HTML links ... done
    df_NG_biomarker_metadata                html  
    df_demo_metabolic_data                  html  
    df_grouping_all_NG_biomarkers           html  
    df_linear_associations                  html  
    df_logodds_associations                 html  
    discovery_regression                    html  
    forestplot                              html  
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:34: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:40: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:45: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:53: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:57: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/forestplot.Rd:62: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
    geom_effect                             html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/geom_effect.Rd:70: file link 'geom_pointrangeh' in package 'ggstance' does not exist and so has been treated as a topic
    geom_stripes                            html  
    ggforestplot-package                    html  
    ng_colour                               html  
    ng_palette                              html  
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/ng_palette.Rd:21: file link 'colorRampPalette' in package 'grDevices' does not exist and so has been treated as a topic
    ng_scale                                html  
    plot_all_NG_biomarkers                  html  
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:43: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:48: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:54: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:59: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:67: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:71: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/plot_all_NG_biomarkers.Rd:76: file link 'quotation' in package 'rlang' does not exist and so has been treated as a topic
    theme_forest                            html  
Rd warning: C:/Users/alish/AppData/Local/Temp/RtmpyemlGF/R.INSTALLc6c87b7a42c5/ggforestplot/man/theme_forest.Rd:22: file link 'theme_minimal' in package 'ggplot2' does not exist and so has been treated as a topic
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'ggforestplot':
 .onLoad failed in loadNamespace() for 'broom', details:
  call: library.dynam(lib, package, package.lib)
  error: DLL 'backports' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/alish/OneDrive/My Documents/R/win-library/4.0/ggforestplot'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/alish/AppData/Local/Temp/RtmpUpSUza/file11204744715f/ggforestplot_0.1.0.tar.gz’ had non-zero exit status

**Comment by mariakalimeri** [comment] 2021-04-10 14:56
Thanks for pointing this out. I don't have Windows handy atm to try to reproduce this but I feel your problem is not specific to `ggforestplot`. It seems to me that the `broom` dependency is not installed because, in turn, it's own `backports` r package cannot be installed. Even more so, they are both the first package in the their respective lists of dependencies so it may not even have to do with them. Or it might, I don't know. Can you try maybe installing `backports` (from source if the other way doesn't work)? And if this succeeds then install `broom`?

**Comment by mariakalimeri** [comment] 2021-06-29 08:12
Here is a docker solution posted on a similar issue 

https://github.com/NightingaleHealth/ggforestplot/issues/5#issuecomment-870378959

Let's close this one as well

**Closed as completed** 2021-07-05 09:52 UTC
